// <auto-generated />
using System;

using HiTechStore.Infrastructure.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiTechStore.Migrations
{
    [DbContext(typeof(HiTechStoreDbContext))]
    [Migration("20260221221649_AddEntityPropertyIdColumn")]
    partial class AddEntityPropertyIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiTechStore.Core.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("BrandId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.BrandModel", b =>
                {
                    b.Property<int>("BrandModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandModelId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("BrandModelId");

                    b.HasIndex("BrandId");

                    b.HasIndex("NormalizedName", "BrandId")
                        .IsUnique();

                    b.ToTable("BrandModel");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CartId");

                    b.HasIndex("ClientId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int?>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductVariationId")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductVariationId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.CategoryComponent", b =>
                {
                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentTypeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryComponent");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ColorId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentModel", b =>
                {
                    b.Property<int>("ComponentModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentModelId"));

                    b.Property<int?>("BrandModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComponentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ComponentModelId");

                    b.HasIndex("BrandModelId");

                    b.HasIndex("ComponentTypeId", "BrandModelId")
                        .IsUnique();

                    b.ToTable("ComponentModel");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentPropertyValue", b =>
                {
                    b.Property<int>("ComponentPropertyValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentPropertyValueId"));

                    b.Property<int?>("ComponentModelId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentPropertyValueId");

                    b.HasIndex("ComponentModelId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ComponentPropertyValue");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentType", b =>
                {
                    b.Property<int>("ComponentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ComponentTypeId");

                    b.ToTable("ComponentType");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountCode", b =>
                {
                    b.Property<int>("DiscountCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountCodeId"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscountCodeId");

                    b.ToTable("DiscountCodes", (string)null);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountCondition", b =>
                {
                    b.Property<int>("DiscountConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountConditionId"));

                    b.Property<int?>("DiscountConditionGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityPropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("DiscountConditionId");

                    b.HasIndex("DiscountConditionGroupId");

                    b.HasIndex("EntityPropertyId");

                    b.ToTable("DiscountCondition");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountConditionGroup", b =>
                {
                    b.Property<int>("DiscountConditionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountConditionGroupId"));

                    b.Property<int>("DiscountRuleId")
                        .HasColumnType("integer");

                    b.HasKey("DiscountConditionGroupId");

                    b.HasIndex("DiscountRuleId");

                    b.ToTable("DiscountConditionGroup");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountEntity", b =>
                {
                    b.Property<int>("DiscountEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountEntityId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DiscountEntityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiscountEntities", (string)null);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountEntityProperty", b =>
                {
                    b.Property<int>("DiscountEntityPropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountEntityPropertyId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("SubEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("DiscountEntityPropertyId");

                    b.HasIndex("SubEntityId");

                    b.HasIndex("EntityId", "Name")
                        .IsUnique();

                    b.ToTable("DiscountEntityProperties", (string)null);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountRule", b =>
                {
                    b.Property<int>("DiscountRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountRuleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DiscountCodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DiscountRuleId");

                    b.HasIndex("DiscountCodeId");

                    b.ToTable("DiscountRules", (string)null);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentState")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("Discount")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<double>("OrderPayTimePrice")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProductVariationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariationId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<int?>("BrandModelId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsDeleled")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BrandModelId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductMedia", b =>
                {
                    b.Property<int>("ProductMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductMediaId"));

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductVariationId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ProductMediaId");

                    b.HasIndex("ProductVariationId");

                    b.ToTable("ProductMedia");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductPropertyValue", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductPropertyValue")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "PropertyId");

                    b.HasIndex("ProductPropertyValue");

                    b.HasIndex("PropertyId");

                    b.ToTable("ProductPropertyValue");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductScore", b =>
                {
                    b.Property<int>("ProductScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductScoreId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ProductScoreId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProductId", "UserId")
                        .IsUnique();

                    b.ToTable("ProductScores");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductVariation", b =>
                {
                    b.Property<int>("ProductVariationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductVariationId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("Inventory")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("ProductVariationId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariation");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropertyId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComponentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("PropertyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.PropertyValue", b =>
                {
                    b.Property<int>("PropertyValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropertyValueId"));

                    b.Property<int>("ComponentPropertyValueId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ValueDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ValueNumber")
                        .HasColumnType("double precision");

                    b.Property<int?>("ValueReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ValueString")
                        .HasColumnType("text");

                    b.HasKey("PropertyValueId");

                    b.HasIndex("ComponentPropertyValueId")
                        .IsUnique();

                    b.ToTable("PropertyValue");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductComponents", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentModelId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ComponentModelId");

                    b.HasIndex("ComponentModelId");

                    b.HasIndex("ProductId", "ComponentModelId")
                        .IsUnique();

                    b.ToTable("ProductComponents");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.BrandModel", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Cart", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.CartItem", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HiTechStore.Core.Models.ProductVariation", "ProductVariation")
                        .WithMany()
                        .HasForeignKey("ProductVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariation");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.CategoryComponent", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.ComponentType", "Component")
                        .WithMany("Categories")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentModel", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.BrandModel", "BrandModel")
                        .WithMany()
                        .HasForeignKey("BrandModelId");

                    b.HasOne("HiTechStore.Core.Models.ComponentType", "ComponentType")
                        .WithMany("ComponentModels")
                        .HasForeignKey("ComponentTypeId");

                    b.Navigation("BrandModel");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentPropertyValue", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.ComponentModel", "ComponentModel")
                        .WithMany("Properties")
                        .HasForeignKey("ComponentModelId");

                    b.HasOne("HiTechStore.Core.Models.Property", "Property")
                        .WithMany("ComponentValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentModel");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountCondition", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.DiscountConditionGroup", null)
                        .WithMany("Conditions")
                        .HasForeignKey("DiscountConditionGroupId");

                    b.HasOne("HiTechStore.Core.Models.DiscountEntityProperty", "EntityProperty")
                        .WithMany()
                        .HasForeignKey("EntityPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityProperty");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountConditionGroup", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.DiscountRule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("DiscountRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountEntityProperty", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.DiscountEntity", "Entity")
                        .WithMany("Properties")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.DiscountEntity", "SubEntity")
                        .WithMany()
                        .HasForeignKey("SubEntityId");

                    b.Navigation("Entity");

                    b.Navigation("SubEntity");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountRule", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.DiscountCode", null)
                        .WithMany("Rules")
                        .HasForeignKey("DiscountCodeId");

                    b.OwnsOne("HiTechStore.Core.Models.DiscountAction", "DiscountAction", b1 =>
                        {
                            b1.Property<int>("DiscountRuleId")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("DiscountRuleId");

                            b1.ToTable("DiscountRules");

                            b1.WithOwner()
                                .HasForeignKey("DiscountRuleId");
                        });

                    b.Navigation("DiscountAction");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Order", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.OrderItem", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HiTechStore.Core.Models.ProductVariation", "ProductVariation")
                        .WithMany()
                        .HasForeignKey("ProductVariationId");

                    b.Navigation("Order");

                    b.Navigation("ProductVariation");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Product", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("HiTechStore.Core.Models.BrandModel", "BrandModel")
                        .WithMany()
                        .HasForeignKey("BrandModelId");

                    b.HasOne("HiTechStore.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BrandModel");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductMedia", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.ProductVariation", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductVariationId");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductPropertyValue", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Product", "Product")
                        .WithMany("Properties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.PropertyValue", "Value")
                        .WithMany()
                        .HasForeignKey("ProductPropertyValue");

                    b.HasOne("HiTechStore.Core.Models.Property", "Property")
                        .WithMany("ProductValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Property");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductScore", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Product", null)
                        .WithMany("Scores")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductVariation", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.Product", "Product")
                        .WithMany("Variations")
                        .HasForeignKey("ProductId");

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Property", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.Category", null)
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HiTechStore.Core.Models.ComponentType", null)
                        .WithMany("Properties")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HiTechStore.Core.Models.PropertyValue", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.ComponentPropertyValue", null)
                        .WithOne("Value")
                        .HasForeignKey("HiTechStore.Core.Models.PropertyValue", "ComponentPropertyValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductComponents", b =>
                {
                    b.HasOne("HiTechStore.Core.Models.ComponentModel", null)
                        .WithMany()
                        .HasForeignKey("ComponentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiTechStore.Core.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Category", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentModel", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentPropertyValue", b =>
                {
                    b.Navigation("Value");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ComponentType", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ComponentModels");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountCode", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountConditionGroup", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.DiscountRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Product", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Scores");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.ProductVariation", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("HiTechStore.Core.Models.Property", b =>
                {
                    b.Navigation("ComponentValues");

                    b.Navigation("ProductValues");
                });
#pragma warning restore 612, 618
        }
    }
}
