<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1916c01c-9a95-4ad0-8a0a-97bd408dc502</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Bogus" Version="35.6.3" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNet.SignalR" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HiTechPay.Sdk\HiTechPay.Sdk.csproj" />
    <ProjectReference Include="..\HiTechStore.ApiTokenHandler\HiTechStore.ApiTokenHandler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Services\Order\" />
    <Folder Include="Data\DTOs\DiscountCode\" />
    <Folder Include="Data\DTOs\DiscountEntity\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Infrastructure\Email\Templates\**\*.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- 
    Bug of assembling static files in .NET 9.0.
    https://github.com/dotnet/aspnetcore/issues/59625
  -->
  <Target Name="CustomClean" BeforeTargets="Restore">
    <Message Text="&gt;&gt;&gt; Custom clean is running" Importance="high" />
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" />
    <RemoveDir Directories="$(BaseOutputPath)" />
  </Target>
</Project>
