<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultWatchItems>false</EnableDefaultWatchItems>
    <UserSecretsId>b09accaf-2282-41b7-bd5c-37ce6953dded</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <UpToDateCheckBuilt Include="frontend/input.css" Set="Css" />
    <UpToDateCheckBuilt Include="tailwind.config.js" Set="Css" />
    <Watch Include="**/*.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HiTechPay.Sdk\HiTechPay.Sdk.csproj" />
  </ItemGroup>

  <Target Name="Tailwind" BeforeTargets="Build">
    <Exec Command="npm run watch" WorkingDirectory="./frontend" />
  </Target>

    <!-- 
    Bug of assembling static files in .NET 9.0.
    https://github.com/dotnet/aspnetcore/issues/59625
  -->
  <Target Name="CustomClean" BeforeTargets="Restore">
    <Message Text="&gt;&gt;&gt; Custom clean is running" Importance="high" />
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" />
    <RemoveDir Directories="$(BaseOutputPath)" />
  </Target>
</Project>
